spring:
  application:
    name: service-1
# spring-boot 2.0 默认使用Hikaripoool
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: liuyun123
      url: jdbc:mysql://localhost:3306/spring_cloud_demo

server:
  port: 8011

#注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: mapper/*.xml



