spring:
  application:
    name: hystrix

server:
  port: 8038
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000


